version: '3.8'

services:
  app:
    container_name: procycling-scraper-app
    ports:
      - "8000:8000"
    build: .
    volumes:
      - ./src:/app/src
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/procyclingdb
    depends_on:
      - db
    networks:
      - procycling-net
    command: tail -f /dev/null
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  db:
    container_name: procycling-scraper-db
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - procycling-net
  
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - procycling-net
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - procycling-net

networks:
  procycling-net:
    driver: bridge

volumes:
  postgres_data: