version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/procyclingdb

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=procyclingdb
    ports:
      - "5432:5432"

volumes:
  postgres_data: