apiVersion: 1

# Automatically provision Loki datasource in Grafana

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    jsonData:
      maxLines: 1000
