# Kamal deployment config
service: procycling-scraper
image: egimenos/cycling-fantasy-league-analyzer

# Target servers (Docker installed, SSH reachable)
servers:
  - "<%= ENV['APP_SERVER'] %>"

# SSH settings
ssh:
  user: "deploy"
  # port: 22

# Container registry (GHCR)
registry:
  server: ghcr.io
  username: "<%= ENV['REGISTRY_USERNAME'] %>"
  password: "<%= ENV['REGISTRY_PASSWORD'] %>"

# Configure builder architecture to match server
builder:
  arch: amd64

# Environment passed to the app container
env:
  clear:
    PORT: 80
    DATABASE_URL: "<%= ENV['DATABASE_URL'] %>"

# Use Traefik via kamal-proxy to expose the app on port 80 without a domain
labels:
  traefik.enable: "true"
  traefik.http.routers.procycling-scraper.rule: "PathPrefix(`/`)"
  traefik.http.routers.procycling-scraper.entrypoints: "web"
  traefik.http.services.procycling-scraper.loadbalancer.server.port: "80"

# Postgres accessory managed by Kamal (data persisted on host)
accessories:
  postgres:
    hosts:
      - "<%= ENV['APP_SERVER'] %>"
    image: postgres:15-alpine
    env:
      clear:
        POSTGRES_DB: procycling
        POSTGRES_USER: procycling
        POSTGRES_PASSWORD: "<%= ENV['POSTGRES_PASSWORD'] %>"
    volumes:
      - "/var/lib/procycling-scraper-postgres:/var/lib/postgresql/data"
