name: Docker Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image (no push)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: procycling-scraper:ci
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
