name: Dockerfile Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: docker-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
