name: Lint & Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install linters/formatters
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 isort

      - name: Black (check)
        run: black --check .

      - name: isort (check)
        run: isort --profile black --check-only .

      - name: Flake8 (lint)
        run: flake8 src tests
